
/* 
File:        01_load_raw_staging_table.sql
Description: serves as a staging table (part_d_2023_raw)
             - defines all columns as TEXT data type before importing CSV data into SQL Shell (psql)
             - prevents data import failure even on empty or malformed cells
Author:      John Ofoegbu
*/

--create staging table
CREATE TABLE part_d_2023_raw (
PRSCRBR_NPI TEXT,
Prscrbr_Last_Org_Name  TEXT,
Prscrbr_First_Name  TEXT,
Prscrbr_MI  TEXT,
Prscrbr_Crdntls  TEXT,
Prscrbr_Ent_Cd  TEXT,
Prscrbr_St1  TEXT,
Prscrbr_St2  TEXT,
Prscrbr_City  TEXT,
Prscrbr_State_Abrvtn  TEXT,
Prscrbr_State_FIPS  TEXT,
Prscrbr_zip5  TEXT,
Prscrbr_RUCA  TEXT,
Prscrbr_RUCA_Desc  TEXT,
Prscrbr_Cntry  TEXT,
Prscrbr_Type  TEXT,
Prscrbr_Type_src  TEXT,
Tot_Clms  TEXT,
Tot_30day_Fills  TEXT,
Tot_Drug_Cst  TEXT,
Tot_Day_Suply  TEXT,
Tot_Benes  TEXT,
GE65_Sprsn_Flag  TEXT,
GE65_Tot_Clms  TEXT,
GE65_Tot_30day_Fills  TEXT,
GE65_Tot_Drug_Cst  TEXT,
GE65_Tot_Day_Suply  TEXT,
GE65_Bene_Sprsn_Flag  TEXT,
GE65_Tot_Benes  TEXT,
Brnd_Sprsn_Flag  TEXT,
Brnd_Tot_Clms  TEXT,
Brnd_Tot_Drug_Cst  TEXT,
Gnrc_Sprsn_Flag  TEXT,
Gnrc_Tot_Clms  TEXT,
Gnrc_Tot_Drug_Cst  TEXT,
Othr_Sprsn_Flag  TEXT,
Othr_Tot_Clms  TEXT,
Othr_Tot_Drug_Cst  TEXT,
MAPD_Sprsn_Flag  TEXT,
MAPD_Tot_Clms  TEXT,
MAPD_Tot_Drug_Cst  TEXT,
PDP_Sprsn_Flag  TEXT,
PDP_Tot_Clms  TEXT,
PDP_Tot_Drug_Cst  TEXT,
LIS_Sprsn_Flag  TEXT,
LIS_Tot_Clms  TEXT,
LIS_Drug_Cst  TEXT,
NonLIS_Sprsn_Flag  TEXT,
NonLIS_Tot_Clms  TEXT,
NonLIS_Drug_Cst  TEXT,
Opioid_Tot_Clms  TEXT,
Opioid_Tot_Drug_Cst  TEXT,
Opioid_Tot_Suply  TEXT,
Opioid_Tot_Benes  TEXT,
Opioid_Prscrbr_Rate  TEXT,
Opioid_LA_Tot_Clms  TEXT,
Opioid_LA_Tot_Drug_Cst  TEXT,
Opioid_LA_Tot_Suply  TEXT,
Opioid_LA_Tot_Benes  TEXT,
Opioid_LA_Prscrbr_Rate  TEXT,
Antbtc_Tot_Clms  TEXT,
Antbtc_Tot_Drug_Cst  TEXT,
Antbtc_Tot_Benes  TEXT,
Antpsyct_GE65_Sprsn_Flag  TEXT,
Antpsyct_GE65_Tot_Clms  TEXT,
Antpsyct_GE65_Tot_Drug_Cst  TEXT,
Antpsyct_GE65_Bene_Suprsn_Flag  TEXT,
Antpsyct_GE65_Tot_Benes  TEXT,
Bene_Avg_Age  TEXT,
Bene_Age_LT_65_Cnt TEXT,
Bene_Age_65_74_Cnt  TEXT,
Bene_Age_75_84_Cnt  TEXT,
Bene_Age_GT_84_Cnt  TEXT,
Bene_Feml_Cnt  TEXT,
Bene_Male_Cnt  TEXT,
Bene_Race_Wht_Cnt  TEXT,
Bene_Race_Black_Cnt  TEXT,
Bene_Race_Api_Cnt  TEXT,
Bene_Race_Hspnc_Cnt  TEXT,
Bene_Race_Natind_Cnt  TEXT,
Bene_Race_Othr_Cnt  TEXT,
Bene_Dual_Cnt  TEXT,
Bene_Ndual_Cnt  TEXT,
Bene_Avg_Risk_Scre  TEXT
);
